# ReviewReplier
# Используем официальный образ Python
FROM python:3.9

# Установка рабочей директории
WORKDIR /app

# Копирование файлов проекта
COPY bot.py requirements.txt welcome_image.jpg ./

# Установка зависимостей
RUN pip install --no-cache-dir -r requirements.txt

# Команда для запуска бота
CMD ["python", "bot.py"]
