FROM python:3.9

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Подключаем PYTHONPATH, чтобы Python видел /app как корень для пакета app
ENV PYTHONPATH=/app

CMD ["python", "app/bot/bot.py"]