version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    image: review-replier-bot:latest
    env_file:
      - .env.bot
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: review-replier-backend:latest
    env_file:
      - .env.backend
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
