# ReviewReplier
# Используем официальный образ Python
FROM python:3.9

# Установка рабочей директории
WORKDIR /app

# Копирование файлов проекта
COPY main.py requirements.txt ./

# Установка зависимостей
RUN pip install --no-cache-dir -r requirements.txt

# Команда для запуска бэкенда
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
