"""Initial migration

Revision ID: 3c7266e0696d
Revises: 
Create Date: 2024-11-20 16:42:00.767253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7266e0696d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'gpt_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('gpt_settings', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
