"""Remove api_keys and marketplaces from User

Revision ID: 89a2e3d9c255
Revises: c1772fd60a4e
Create Date: 2024-11-20 17:54:42.316414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a2e3d9c255'
down_revision: Union[str, None] = 'c1772fd60a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
